---
- name: restart fail2ban
  service: name=fail2ban state=restarted
- name: restart ssh
  service: name=ssh state=restarted
- name: activate firewall rules
  shell: iptables-restore < /etc/iptables.firewall.rules; iptables -L -n > /etc/iptables.initial.state
